### ISSUE TITLE
Searchable items in one room

### ISSUE THREAD

**Issue by JohnBoyJohn** [DidiCatman/Team_Z#4]
1. Can be more than one treasure in one room? 
2. Can a treasure have more than one item?
3. Should there be an icon for a looted room?

LG JohnBoyJohn

**Comment by DidiCatman** [comment]
1. Normally infinite number of treasures per room, but only one search action per hero and turn.
2. One search action is one item (but when you have a torch you can search 2).
3. Icon only in special scenarios when there is only one item per room.
